package com.main.pojo;
// Generated May 5, 2016 4:40:48 AM by Hibernate Tools 3.6.0



/**
 * TblProfile generated by hbm2java
 */
public class TblProfile  implements java.io.Serializable {


     private Integer id;
     private String fullName;
     private String contactNo;
     private String landLineNo;
     private String emailId;
     private String password;
     private String securityQuestion;
     private String answer;
     private String collegeName;
     private String collegeAddress;
     private String collegeTime;
     private int noOfBranches;
     private Character isActive;

    public TblProfile() {
    }

	
    public TblProfile(String fullName, String contactNo, String emailId, String password, String securityQuestion, String answer, String collegeName, String collegeAddress, String collegeTime, int noOfBranches) {
        this.fullName = fullName;
        this.contactNo = contactNo;
        this.emailId = emailId;
        this.password = password;
        this.securityQuestion = securityQuestion;
        this.answer = answer;
        this.collegeName = collegeName;
        this.collegeAddress = collegeAddress;
        this.collegeTime = collegeTime;
        this.noOfBranches = noOfBranches;
    }
    public TblProfile(String fullName, String contactNo, String landLineNo, String emailId, String password, String securityQuestion, String answer, String collegeName, String collegeAddress, String collegeTime, int noOfBranches, Character isActive) {
       this.fullName = fullName;
       this.contactNo = contactNo;
       this.landLineNo = landLineNo;
       this.emailId = emailId;
       this.password = password;
       this.securityQuestion = securityQuestion;
       this.answer = answer;
       this.collegeName = collegeName;
       this.collegeAddress = collegeAddress;
       this.collegeTime = collegeTime;
       this.noOfBranches = noOfBranches;
       this.isActive = isActive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getLandLineNo() {
        return this.landLineNo;
    }
    
    public void setLandLineNo(String landLineNo) {
        this.landLineNo = landLineNo;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSecurityQuestion() {
        return this.securityQuestion;
    }
    
    public void setSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getCollegeName() {
        return this.collegeName;
    }
    
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }
    public String getCollegeAddress() {
        return this.collegeAddress;
    }
    
    public void setCollegeAddress(String collegeAddress) {
        this.collegeAddress = collegeAddress;
    }
    public String getCollegeTime() {
        return this.collegeTime;
    }
    
    public void setCollegeTime(String collegeTime) {
        this.collegeTime = collegeTime;
    }
    public int getNoOfBranches() {
        return this.noOfBranches;
    }
    
    public void setNoOfBranches(int noOfBranches) {
        this.noOfBranches = noOfBranches;
    }
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }




}


