package com.eew.pojo;
// Generated May 11, 2016 12:28:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblProfile generated by hbm2java
 */
public class TblProfile  implements java.io.Serializable {


     private Integer id;
     private String fullName;
     private String contactNo;
     private String landLineNo;
     private String emailId;
     private String password;
     private String securityQuestion;
     private String answer;
     private String collegeName;
     private String collegeAddress;
     private String collegeTime;
     private int noOfBranches;
     private Character isActive;
     private Set tblGroupStudents = new HashSet(0);
     private Set tblHods = new HashSet(0);
     private Set tblGuides = new HashSet(0);
     private Set tblProjectGroups = new HashSet(0);

    public TblProfile() {
    }

	
    public TblProfile(String fullName, String contactNo, String emailId, String password, String securityQuestion, String answer, String collegeName, String collegeAddress, String collegeTime, int noOfBranches) {
        this.fullName = fullName;
        this.contactNo = contactNo;
        this.emailId = emailId;
        this.password = password;
        this.securityQuestion = securityQuestion;
        this.answer = answer;
        this.collegeName = collegeName;
        this.collegeAddress = collegeAddress;
        this.collegeTime = collegeTime;
        this.noOfBranches = noOfBranches;
    }
    public TblProfile(String fullName, String contactNo, String landLineNo, String emailId, String password, String securityQuestion, String answer, String collegeName, String collegeAddress, String collegeTime, int noOfBranches, Character isActive, Set tblGroupStudents, Set tblHods, Set tblGuides, Set tblProjectGroups) {
       this.fullName = fullName;
       this.contactNo = contactNo;
       this.landLineNo = landLineNo;
       this.emailId = emailId;
       this.password = password;
       this.securityQuestion = securityQuestion;
       this.answer = answer;
       this.collegeName = collegeName;
       this.collegeAddress = collegeAddress;
       this.collegeTime = collegeTime;
       this.noOfBranches = noOfBranches;
       this.isActive = isActive;
       this.tblGroupStudents = tblGroupStudents;
       this.tblHods = tblHods;
       this.tblGuides = tblGuides;
       this.tblProjectGroups = tblProjectGroups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getLandLineNo() {
        return this.landLineNo;
    }
    
    public void setLandLineNo(String landLineNo) {
        this.landLineNo = landLineNo;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSecurityQuestion() {
        return this.securityQuestion;
    }
    
    public void setSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getCollegeName() {
        return this.collegeName;
    }
    
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }
    public String getCollegeAddress() {
        return this.collegeAddress;
    }
    
    public void setCollegeAddress(String collegeAddress) {
        this.collegeAddress = collegeAddress;
    }
    public String getCollegeTime() {
        return this.collegeTime;
    }
    
    public void setCollegeTime(String collegeTime) {
        this.collegeTime = collegeTime;
    }
    public int getNoOfBranches() {
        return this.noOfBranches;
    }
    
    public void setNoOfBranches(int noOfBranches) {
        this.noOfBranches = noOfBranches;
    }
    public Character getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Character isActive) {
        this.isActive = isActive;
    }
    public Set getTblGroupStudents() {
        return this.tblGroupStudents;
    }
    
    public void setTblGroupStudents(Set tblGroupStudents) {
        this.tblGroupStudents = tblGroupStudents;
    }
    public Set getTblHods() {
        return this.tblHods;
    }
    
    public void setTblHods(Set tblHods) {
        this.tblHods = tblHods;
    }
    public Set getTblGuides() {
        return this.tblGuides;
    }
    
    public void setTblGuides(Set tblGuides) {
        this.tblGuides = tblGuides;
    }
    public Set getTblProjectGroups() {
        return this.tblProjectGroups;
    }
    
    public void setTblProjectGroups(Set tblProjectGroups) {
        this.tblProjectGroups = tblProjectGroups;
    }




}


